const { REACT_APP_BASE_URL_GQL, REACT_APP_BASE_URL_REST } = process.env;

export const BASE_URL_GQL = REACT_APP_BASE_URL_GQL;
export const BASE_URL_REST = REACT_APP_BASE_URL_REST;

export const IS_MOCKUP = REACT_APP_BASE_URL_REST;